services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - .env

  meel:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./data:/usr/src/meel/data
