services:
  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    env_file:
      - .env.production
    volumes:
      - data:/var/lib/postgresql/data

  meel:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env.production
    depends_on:
      - db
    volumes:
      - ./data:/data

volumes:
  data:
