name: Build Docker Image

inputs:
  tag:
    description: 'Docker image tag'
    required: true

runs:
  using: "docker"
  steps:
    - uses: docker/setup-buildx-action@v3
    - name: Build the Docker image
      shell: bash
      run: docker build . --file Dockerfile --tag meel:${{ inputs.tag }}
