[package]
name = "meel-templating"
version = "0.1.0"
edition = "2024"

[dependencies]
ammonia = "4.1.2"
minify-html = "0.16.4"
regex = "1.11.3"
serde_json = "1.0.145"
mustache = "0.9.0"
meel-utils = { path = "../meel-utils" }
