name: CI Backend

on:
  push:
    branches:
      - '*'
    paths:
      - "crates/meel-backend/**"
      - "crates/meel-utils/**"
      - "crates/meel-templating/**"
      - "docker/Dockerfile"
      - "docker/full.Dockerfile"
      - ".github/workflows/ci-backend.yml"
  pull_request:
    branches:
      - '*'
    paths:
      - "crates/meel-backend/**"
      - "crates/meel-utils/**"
      - "crates/meel-templating/**"
      - "docker/Dockerfile"
      - "docker/full.Dockerfile"

jobs:
  build-regular:
    name: Build Backend Regular
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker tag
        id: set_tag
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
              echo "tag=ghcr.io/borisnliscool/meel:latest" >> $GITHUB_ENV
          else
              echo "tag=ghcr.io/borisnliscool/meel:${GITHUB_REF##*/}" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.tag }}

  build-full:
    name: Build Backend Full
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker tag
        id: set_tag
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
              echo "tag=ghcr.io/borisnliscool/meel-full:latest" >> $GITHUB_ENV
          else
              echo "tag=ghcr.io/borisnliscool/meel-full:${GITHUB_REF##*/}" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./full.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.tag }}
