name: CI Backend

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - "Dockerfile"
      - ".github/workflows/ci-backend.yml"
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"
      - "Dockerfile"

jobs:
  build:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker tag
        id: set_tag
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
              echo "tag=ghcr.io/borisnliscool/meel:latest" >> $GITHUB_ENV
          else
              echo "tag=ghcr.io/borisnliscool/meel:${GITHUB_REF##*/}" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.tag }}
