name: CI Backend

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - "Dockerfile"
      - ".github/workflows/ci-backend.yml"
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  build:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag meel:$(date +%s)
