name: CI Node SDK

on:
  push:
    branches:
      - '*'
    paths:
      - "sdk/node/**"
      - ".github/workflows/ci-sdk-node.yml"
  pull_request:
    branches:
      - '*'
    paths:
      - "sdk/node/**"

jobs:
  build:
    name: Build Node SDK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: sdk/node
        run: bun install

      - name: Lint
        working-directory: sdk/node
        run: bun run lint

      - name: Build SDK
        working-directory: sdk/node
        run: bun run build
