name: CI Tool VSCode

on:
  push:
    branches:
      - main
    paths:
      - "tooling/meel-vscode/**"
  pull_request:
    branches:
      - main
    paths:
      - "tooling/meel-vscode/**"

jobs:
  build:
    name: Build VSCode Extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        working-directory: tooling/meel-vscode
        run: pnpm install --frozen-lockfile
      - name: Install vsce
        run: pnpm install -g vsce
      - name: Package VSCode Extension
        working-directory: tooling/meel-vscode
        run: pnpm run vsce package