name: CI Tool VSCode

on:
  push:
    branches:
      - main
    paths:
      - "tooling/meel-vscode/**"
      - ".github/workflows/ci-tool-vscode.yml"
  pull_request:
    branches:
      - main
    paths:
      - "tooling/meel-vscode/**"

jobs:
  build:
    name: Build VSCode Extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          package_json_file: tooling/meel-vscode/package.json

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: tooling/meel-vscode/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: tooling/meel-vscode
        run: pnpm install --frozen-lockfile

      - name: Lint
        working-directory: tooling/meel-vscode
        run: pnpm lint

      - name: Install @vscode/vsce
        run: pnpm install -g @vscode/vsce

      - name: Copy license for vsce
        run: cp LICENSE tooling/meel-vscode

      - name: Package VSCode Extension
        working-directory: tooling/meel-vscode
        run: pnpm vsce package --no-dependencies
