name: Release Backend

on:
  push:
    tags:
      - '*'
    paths:
      - "crates/meel-backend/**"
      - "crates/meel-utils/**"
      - "crates/meel-templating/**"
      - "docker/Dockerfile"
      - "docker/full.Dockerfile"

jobs:
  build-regular:
    name: Release Backend Regular
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and push
        uses: docker/build-push-action@v3
        with:
          file: ./docker/Dockerfile
          push: true
          tags: |
            borisnl/meel:${{ github.ref_name }}
            borisnl/meel:latest

  build-full:
    name: Release Backend Full
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and push
        uses: docker/build-push-action@v3
        with:
          file: ./docker/full.Dockerfile
          push: true
          tags: |
            borisnl/meel-full:${{ github.ref_name }}
            borisnl/meel-full:latest