on:
  push:
    tags:
      - '*'
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bump version in Cargo.toml
        run: sed -i "s/^version = \".*\"/version = \"${{ github.ref_name }}\"/" backend/Cargo.toml

      - name: Push package change
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.event.repository.default_branch }}
          commit_message: 'chore: bump Cargo.toml version to ${{ github.ref_name }}'
          commit_user_name: Version bumper
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          file_pattern: backend/Cargo.toml

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          tags: |
            borisnl/meel:${{ github.ref_name }}
            borisnl/meel:latest